# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: benfry
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: music-site
# "service" is the name of this project. This will also be added to your AWS resource names.
service: music

custom:
  wsgi:
    app: app.app
  customDomain:
    domainName: api.benfrymusic.com
    basePath: ''
    stage: dev
    createRoute53Record: true


provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-07346a9bec365e699
    subnetIds:
      - subnet-03b1a0533ac529873
      - subnet-04b852657210affdb
      - subnet-039f3c87afd9f4a02
      - subnet-0de606814581f9497
      - subnet-0ee720bf096c9cd2c
      - subnet-0a4a7bda22ffc77fa
  runtime: python3.12

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    environment: ${file(env.json)}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
