# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: benfry
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: music-site
# "service" is the name of this project. This will also be added to your AWS resource names.
service: music

custom:
  wsgi:
    app: app.app
  customDomain:
    domainName: api.benfrymusic.com
    basePath: ''
    stage: dev
    createRoute53Record: true


provider:
  name: aws
  runtime: python3.12

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
