name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Production
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - run: npm ci
    - name: install serverless
      run: npm install -g serverless
    - name: install requirements
      run: pip install -r requirements.txt
    - name: Enter dir and deploy
      run: serverless deploy --param="mysql_pwd=${{ secrets.MYSQL_PWD }}"
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
